### ISSUE TITLE
Enable options on a per route basis

### ISSUE THREAD

**Issue by battlejj** [battlejj/express-force-ssl#18]
There is some interest in being able to define options on a per route basis instead of just globally on/off behavior. This could possibly require a usage change and major version bump requirement.

**Comment by vsimonian** [comment]
This would definitely be very useful, especially in a large application that may have very different needs for different routes. Even with a major version bump and breaking changes, I feel it would be worth the cost.

**Comment by battlejj** [comment]
@vsimonian I've added per route config without a breaking change in a separate branch with 53bda5c4ceab061ee0a9e1992511ffecb25c86dd would you mind reviewing and letting me know if you think this is an acceptable way forward?

**Comment by battlejj** [comment]
This has been added to in version 0.3.0 via #26

**Comment by vsimonian** [comment]
Whoops! I thought I responded; my bad. Looks good in 0.3.0!
