### ISSUE TITLE
Additional Options Support

### ISSUE THREAD

**Issue by battlejj** [battlejj/express-force-ssl#19]
Two new options currently being requested:

- 308 Redirect Support
- 403 SSL Required Errors For GET Requests

308 Redirect Support
---------------------------
A 308 Redirect is similar to a permanent redirect, except it is intended for non-GET requests. In addition to permanently redirecting the user, any additional data (i.e. POST data) would also get sent again to the redirected resource. This is still an experimental status code at this time. 

This feature would be an opt in. The default behavior of the library would be to 403 Error for any non-GET request. A simple flag **enable308** could be set to **true** in order to turn this behavior on.

403 SSL Required Errors for GET Requests
-------------------------------------------------------
This feature would also be an opt in. The default behavior of the library would be to 301 Redirect GET requests to the secure location of the resource. Enabling this feature would cause GET requests to behave with the default behavior of any non-GET request and 403 Error. A simple flag of **enableRedirects** (option name is a work in progress, not exactly happy with it) would default to **true**. If this is set to **false** GET requests will return 403 errors if they are not SSL. In addition, if this option is **false** and **enable308** is set to true, 308 redirects WILL NOT work and will 403 Error.

If anyone has any feedback about either of these features I'd be happy to discuss them as their implementation is not yet finalized.

**Comment by vsimonian** [comment]
I am definitely in favour of supporting 403s as an option; I think it would be an invaluable addition. +1

However, I am concerned over the security implications of allowing 308s in a piece of middleware that is designed to enforce SSL connections. Wouldn't it make it easier for a developer to make the mistake of depending on a 308 redirect as a response to an unencrypted HTTP request, and in doing so cause their application to POST sensitive information, unsecured, over the network? I feel it would be much more secure to cause the request to fail, ensuring that the problem would be caught early on.

**Comment by battlejj** [comment]
@vsimonian I agree with you on the 308 redirects, this is why the behavior would have to be an opt-in, the default setting would still be to give 403 Error.

I go back and forth on adding the feature myself, but I feel it's probably best to encourage good coding practice with defaults but not force it on people. There may always be a use case that we cannot think of that this would be a useful option for them to turn on.

**Comment by battlejj** [comment]
The 403 Error for GET requests has been implemented in 53bda5c4ceab061ee0a9e1992511ffecb25c86dd 308s will be kept off the roadmap for now since it is still not even in Proposed Standard status.

**Comment by battlejj** [comment]
These features have been added to version 0.3.0 via #26
