### ISSUE TITLE
req.url gets modified by express next()

### ISSUE THREAD

**Issue by tatepostnikoff** [battlejj/express-force-ssl#20]
the express next() method sometimes trims req.url of the router prefix in lib/router/index.js (trim_prefix)

Has the following comments:
// Trim off the part of the url that matches the route
// middleware (.use stuff) needs to have the path stripped

When I changed your code to use req.originalUrl, it works.

**Comment by battlejj** [comment]
Making this change now.

**Comment by battlejj** [comment]
Good catch and thanks for reporting the issue :+1:

**Comment by tatepostnikoff** [comment]
Hey battlejj, I noticed you made the change to the fullUrl, but not in the redirect, so it still hasn't been fixed.  

req.url -> req.originalUrl

**Comment by battlejj** [comment]
Well that's embarrassing ha. Pushed a new commit, will get it pushed out to npm in a few minutes. Thanks again @tatepostnikoff
