### ISSUE TITLE
Only certain pages SSL

### ISSUE THREAD

**Issue by christiansr85** [battlejj/express-force-ssl#23]
Hello, I'm interested in this module because I'm writting an application which needs to serve some pages under `http` protocol and others under `https`. But I think I've found an issue (maybe it is not an issue, let's see): I've taken your "test/index.js" server file and I've modified it a little, just to try what I want to get. I've added links in lines 29 and 33 of the file:

```javascript
  /*
   Routes
   */
  app.get('/', function (req, res) {
    res.send('HTTP and HTTPS.' + '<br/><a href="/ssl">To ssl</a>');
  });

  app.get('/ssl', forceSSL, function (req, res) {
    res.send('HTTPS only.' + '<br/><a href="/">To http</a><br/><a href="/ssl/nested/route/5">To nesetd ssl</a>');
  });
```

As you can see it is done just to redirect from one page to another. Well, when I launch the application, it is opened in `http` and displays the link to the `ssl` page. That link works fine and redirects to the `https` url specified. 

But in this page, when I click on "To http" link the server redirects to the home page but using `ssl`. Is that the expected behavior? I mean, it should redirect to home page but with `http` protocol, isn't it?

**Comment by battlejj** [comment]
Hey @christiansr85 I will take a look tonight and see if I can replicate this.

**Comment by battlejj** [comment]
Actually, the problem is that your link on your /ssl page is "/", which will relatively resolve to https://localhost/. If you want this to go to the http version of the page, you need your link to point to "http://localhost/" not just "/". So yes, this is expected behavior.
