### ISSUE TITLE
Module should not trust x-forwarded-proto by default

### ISSUE THREAD

**Issue by sebastiang** [battlejj/express-force-ssl#25]
This header can easily be spoofed and should only be trusted if the programmer configures it explicitly.

**Comment by battlejj** [comment]
This is actually a good point. I have actually fixed the code to support this but I have to create additional tests for this functionality. Hopefully will have a patch up this weekend.

**Comment by battlejj** [comment]
@sebastiang this should be addressed in https://github.com/battlejj/express-force-ssl/tree/issues%2319%2C%2325 but before I push to the master branch would you mind reviewing the configuration and tests for X-Forwarded-Proto and let me know if you think it is sufficient?

**Comment by battlejj** [comment]
This has been added to in version 0.3.0 via #26
