### ISSUE TITLE
Deprecated message using express 4.16.3

### ISSUE THREAD

**Issue by joetidee** [battlejj/express-force-ssl#31]
I receive this message when trying to use this package with express:

> express deprecated res.send(status, body): Use res.status(status).send(body) instead node_modules/express-enforces-ssl/index.js:21:7

**Comment by battlejj** [comment]
Thanks @joetidee I'll try to get a patch out for this tonight.

**Comment by joetidee** [comment]
Sorry, my mistake wrong package :( - it was `express-enforces-ssl` - my apologies.

**Comment by battlejj** [comment]
I was going to say, I swore this library was already using `.status` for the longest time 😂 No worries.
